### ISSUE TITLE
Аноны, какой бухгалтерией пользуетесь?

### ISSUE THREAD

**Issue by catamphetamine** [odeskconf/guide#14]
[Альфа-Банк](https://reg-alfabank.ru) мне сразу всучил "Моё Дело", и женщина из техподдержки этого дела с возбуждённым голосом позвонила мне и стала настойчиво уговаривать зайти в личный кабинет и там всё нажать, кому-то что-то отнести, и т.п.. Я сказал, что не сегодня, они сказала, что "я вам позвоню через неделю".
Вот я подумал, такой агрессивный маркетинг, подозрительно — может лучше Эльбу взять.

**Comment by catamphetamine** [comment]
Плюс к этому, можно запилить секцию про то, как в налоговую платить: после каждого квартала 6% от дохода, а доход исчисляется по курсу ЦБ РФ на момент поступления денег на транзитный счёт.
Да и Фонд Стабильности Upwork теперь (по слухам) берёт все 20%, а не 10%, что за гранью разумного.

**Comment by arietis** [comment]
Пользуюсь Эльбой, дело вкуса на самом деле.

**Comment by catamphetamine** [comment]
Я тоже на Эльбе сижу уже год.
Нравится, хоть и старовата судя по виду.
По банку думаю, мб на Тинькова перейти.
Альфу предоплатил на год за 22 тыщи, потом узнал, что в Модуле 10 тыщ, но банки сейчас сыпятся, Тиньков вроде более-менее.
Альфа надёжнее, если нужно знать, что банк не лопнет.
