### ISSUE TITLE
Неточности по поводу вывода средств через ИП

### ISSUE THREAD

**Issue by mr-pokryshkin** [odeskconf/guide#24]
п 7. Паспорт сделки оформляют в том банке, где открыт счет. Это дело контролирует ЦБ, при смене банка - паспорт сделки также переносится из одного банка в другой. Паспорт лучше  открыть раньше, чем сумма достигнет $50000, это не сложно.

> Но у нас есть налог на курсовую разницу, потому эти деньги лучше сразу вывести с долларового счета ИП на долларовый физика.

ИП (по крайней мере на УСН) не платят налог с курсовой разницы кажется с 2013 года.

**Comment by maksimf** [comment]
Я ИП на УСН (до начала текущего года), сейчас на ПСН. И тогда и сейчас платил и плачу налог на курсовую разницу. Можно ссылочку на источник, где есть подтверждение?

**Comment by mr-pokryshkin** [comment]
НК РФ Статья 346.17 пункт 5 и Письмо минфина № 03-11-06/2/1645 от 22.01.2015

**Comment by AlinaRoth** [comment]
@mr-pokryshkin 
https://e-kontur.ru/enquiry/190?_ga=2.92425118.26032609.1532256194-536282908.1514061301

Когда возникают курсовые разницы:

>При переоценке стоимости валюты, когда иностранная валюта остается на вашем счете и её курс меняется. Такая курсовая разница не учитывается с 2013 года.
>При продаже иностранной валюты по курсу выше чем курс ЦБ РФ в этот же день или при покупке валюты по курсу ниже, чем курс ЦБ РФ в этот же день. С такой курсовой разницы нужно заплатить налог.

Таким образом только по первому пункту не надо, по второму - надо, что и делается.

**Comment by mneveroff** [comment]
@mr-pokryshkin
https://e-kontur.ru/enquiry/190?_ga=2.92425118.26032609.1532256194-536282908.1514061301

Когда возникают курсовые разницы:

>При переоценке стоимости валюты, когда иностранная валюта остается на вашем счете и её курс меняется. Такая курсовая разница не учитывается с 2013 года.
>При продаже иностранной валюты по курсу выше чем курс ЦБ РФ в этот же день или при покупке валюты по курсу ниже, чем курс ЦБ РФ в этот же день. С такой курсовой разницы нужно заплатить налог.

Таким образом только по первому пункту не надо, по второму - надо, что и делается.

**Comment by maksimf** [comment]
Спасибо @MNeverOff

**Comment by mr-pokryshkin** [comment]
@MNeverOff эту статью я видел, там сказано:

> Если вы продали иностранную валюту по курсу выше чем курс ЦБ РФ, то у вас возникает доход. 

а в письме минфина сказано:

> с 1 января 2013 года переоценка имущества в виде валютных ценностей и требований (обязательств), стоимость которых выражена в иностранной валюте, в том числе по валютным счетам в банках, в связи с изменением официального курса иностранной валюты к рублю Российской Федерации, установленного Центральным банком Российской Федерации, в целях главы 26.2 Кодекса не производится, доходы и расходы от указанной переоценки не определяются и не учитываются.
Таким образом, с 1 января 2013 года налогоплательщики упрощенной системы налогообложения не должны учитывать как в доходах, так и в расходах положительные и отрицательные курсовые разницы.

Я делаю вывод, что мое имущество это доллары на валютном счете и их переоценка не производится. 
Кроме того, в других статьях и на других сайтах указывается, что курсовая разница не приводит к уплате налогов.
Мой опыт (2 разные налоговые из-за переезда) говорит о том же.

**Comment by mneveroff** [comment]
@mr-pokryshkin 
Опять же, тут правильный вопрос - что есть "переоценка". 
Раньше (до 2013) если бы у вас просто лежали доллары на счету и курс вырос - вам бы _уже_ пришлось уплатить с них налог. Из-за того что они были _переоценены_.
Это убрали, но доход с продажи по другому курсу - остался. Поэтому с него и платится налог.

Думается что ребята в той же Эльбе не зря едят свой хлеб, в то время как налоговые вполне могли закрывать глаза на копейки образующиеся с этих операций.

**Comment by mr-pokryshkin** [comment]
Более полная цитата их статьи:

> Когда возникают курсовые разницы:
При продаже иностранной валюты по курсу выше чем курс ЦБ РФ в этот же день или при покупке валюты по курсу ниже, чем курс ЦБ РФ в этот же день. С такой курсовой разницы нужно заплатить налог.

Т.е. это **курсовая разница**, про которую в НК и письме минфина однозначно сказано:

> налогоплательщики упрощенной системы налогообложения не должны учитывать как в доходах, так и в расходах положительные и отрицательные курсовые разницы.

Верить или не верить коммерческой конторе дело личное. Тем более что ссылок на документы в их статье нет. В НК очень сложно разобраться, но имхо в письме все сказано однозначно.
