### ISSUE TITLE
Разбан

### ISSUE THREAD

**Issue by egslava** [odeskconf/guide#27]
request

**Comment by egslava** [comment]
Пробовал через Хероку, но, почему-то, не приходит инвайт. @maksimf @arietis

**Comment by arietis** [comment]
:proigral:

**Comment by egslava** [comment]
Сергей, добавьте, пожалуйста, не приходит инвайт :-(

**Comment by egslava** [comment]
Или, есть возможность, пинганите, пожалуйста, кого-нибудь из конфу, т.к. у меня доступа нет совсем.

**Comment by egslava** [comment]
@arietis
